language: haskell
ghc:
    - 7.8
    - 7.6
before_script:
    - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
    - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
    - sudo apt-get update -q
    - sudo apt-get install rethinkdb
    - rethinkdb --bind all &
